### ISSUE TITLE
Cast: Allow the user to hide listener count

### ISSUE THREAD

**Issue by leoetlino** [innovate-technologies/control#11]
*Related: https://github.com/Innovate-Technologies/Cast/issues/3*

**Comment by meyskens** [comment]
Shall we place this under "Streams"?

**Comment by leoetlino** [comment]
Depends. Are we going to allow the user to change the setting individually for each stream? (that is, allow them to have a different "show listener count" setting for each stream)

**Comment by meyskens** [comment]
Depends. I currently see no usecase for per stream.

**Comment by leoetlino** [comment]
Me neither. _Streams_ does not seem to be the best place for this setting though… I'm relunctant to add yet another navigation entry to the sidebar, as it's getting longer and longer. The most intuitive would however be a Settings link. Who knows they have to look under Streams to change a _setting_? Maybe we should have a Settings entry and move some links into there, like GeoLock.

**Comment by meyskens** [comment]
2 things under settings is so lonely.
And I don't want it to become this
<img width="943" alt="schermafbeelding 2016-01-25 om 17 58 38" src="https://cloud.githubusercontent.com/assets/1625272/12557905/534abd94-c38d-11e5-96e8-874ecf2a9cc6.png">

**Comment by leoetlino** [comment]
Oh I knew that comparison was going to come up :) yes, I don't want that to happen either, but continuing to add things to the navigation sidebar is not viable. And it's already quite long.

The main issue I have with your suggestion is that most users probably won't be able to find the setting if it's hidden in _Streams_. I wouldn't look there for a setting personally.

**Comment by meyskens** [comment]
Ok but if it is under settings why are the passwords under streams that is a setting right? It is a contol panel aka settings panel. The DJ enable switch was planned to be under streams also.

**Comment by leoetlino** [comment]
Because the password can different for each stream, but the "show listener count" setting is a server-wide setting.

**Comment by leoetlino** [comment]
How about we put it in Streams, but in a separate card? I really don't want it to be mixed with the streams' configuration, since this is global.

**Comment by meyskens** [comment]
Agreed! I think that is best for all future settings like with statistics for example

**Comment by meyskens** [comment]
Oh look this has been fixed by #52
