### ISSUE TITLE
GeoLock icon

### ISSUE THREAD

**Issue by meyskens** [Innovate-Technologies/control#19]
<img width="253" alt="schermafbeelding 2016-02-01 om 20 26 45" src="https://cloud.githubusercontent.com/assets/1625272/12728434/23f54eac-c922-11e5-9030-a7ec2d642338.png">

The GeoLock icon went to 2 separate icons. Not sure if it is a regression or Safari 9.1 (in that case might want more info to file a radar).

**Comment by leoetlino** [comment]
![image](https://cloud.githubusercontent.com/assets/4209061/12728494/59f9922e-c922-11e5-985a-825d8911b45a.png)

test
