### ISSUE TITLE
Remove alternative stream URL field

### ISSUE THREAD

**Issue by leoetlino** [Innovate-Technologies/control#4]
From our private git hosting:

>meyskens: Many people mis-use alternative stream url. Can we add some warnings or something else so people don't use it
>leoetlino: Remove the field from Control, and tell them to open a ticket if they need an alternative stream URL? There's not a lot of people who legitimately need to use an alt URL.

**Comment by meyskens** [comment]
Maybe also in Player? Some seem to put their website there.

**Comment by leoetlino** [comment]
Wow, really? That's… horrifying. However, we don't have any easy way to add an alternative stream URL for Player configuration records, whereas it's easy to do that for app requests. And users should know that they are misusing the feature anyway, since they will get a player which doesn't play anything.

**Comment by meyskens** [comment]
Can de send a HEAD request to the url? If it shows audio/* it is correct if not don't let it save.

**Comment by leoetlino** [comment]
That will fix wrong alt stream URLs, but it won't prevent clients from using the field for a stream hosted on another server. And tbh, it sounds like a lot of work and code to add in comparison to the few clients who *really* need this.

**Comment by meyskens** [comment]
Remove it from both, we'll probably ever build our own admin system where we can set it for player. (big dreams come true)

**Comment by leoetlino** [comment]
Sounds good. In the meantime, the few clients that need it can open a ticket.

**Comment by meyskens** [comment]
:+1:
