### ISSUE TITLE
Error on try to load 

### ISSUE THREAD

**Issue by Toso82** [innovate-technologies/control#66]
@meyskens  Please not hate me what it is wrong here ? 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! control@1.0.0 install: `chmod +x ./lint.sh && ln -sf ../../lint.sh .git/hooks/pre-commit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the control@1.0.0 install script 'chmod +x ./lint.sh && ln -sf ../../lint.sh .git/hooks/pre-commit'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the control package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     chmod +x ./lint.sh && ln -sf ../../lint.sh .git/hooks/pre-commit
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs control
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls control
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Giacomo\Documents\Visual Studio 2015\Projects\control-master\npm-debug.log

**Comment by meyskens** [comment]
(did I ever express hate?) This is because our hooks are written to work on Unix (preferred to be Linux) systems. On Windows systems these commands don't exist.

**Comment by Toso82** [comment]
@meyskens  Because i stress you :) . Ok i switch on linux now. I bealive that is the same on windows but it is no problem.  But after install all well i don't undestand how start pannel. I try to run node app.js in src folder but not work 

/root/Scaricati/control-master/src/app.js:19
import {
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Thanks for your patience

**Comment by meyskens** [comment]
https://github.com/innovate-technologies/control/blob/master/WORKFLOW.md

**Comment by Toso82** [comment]
@meyskens  Thanks thanks thanks !!! I don't see it. The last quaestion from today where i find or satting user to enter in controll pannel. I don't find nothing

**Comment by meyskens** [comment]
What do you mean exactly?

**Comment by Toso82** [comment]
I mean that how can configure user account to log in control pannel http://localhost:8900/log-in or where is the default

**Comment by meyskens** [comment]
Control is only a frontend to ITFrame, all it's requests go to there. ITFrame depends on different systems we use. Currently setting it all up without modifying the code isn't possible.

**Comment by Toso82** [comment]
So you mean that i have also ITFrame configurate on local to try Control? There isn't default user to test in local.

**Comment by meyskens** [comment]
By default it connects to https://itframe.innovatete.ch. Control is a pure front-end application. The system is made to manage a whole cluster of Cast servers, for a single Cast server just using the config.json file and the API is suggested.

**Comment by Toso82** [comment]
ok so it is not possible to try configuration front-end in local only just single cast server without front-end. If i want to try i must to use your service :-) correct?

**Comment by meyskens** [comment]
that's correct

**Comment by Toso82** [comment]
Thanks !! When i have time a do a free cast service to try it is so interest your edeal. When finish to insert autodj i think it is perfect not to depends on centova or something alse
